name: Feature Request
description: Suggest something to add to pyKVFinder!
title: "[ENH]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
         Please search the [issues](https://github.com/LBC-LNBio/pyKVFinder/issues) for relevant feature requests before creating a new feature request.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Briefly describe the problem this feature will solve. (2-4 sentences).
      placeholder: |
        * I'm always frustrated when [...] because [...]
        * I would like it if [...] happened when I [...] because [...]
        * Here is a sample image of what I am asking for [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe a way to accomplish the goals of this feature request.
