name: Build and deploy

on:
  push:
  workflow_dispatch: 

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Set environment variable for macos-latest
        if: matrix.os == 'macos-13'
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=13.0" >> $GITHUB_ENV

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.3

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.os }}
          path: ./wheelhouse/*.whl
      
      - name: Install pyKVFinder
        run: |
          pip install wheelhouse/*${{ matrix.os }}.whl
          pyKVFinder pyKVFinder/data/tests/1FMO.pdb --verbose

  pypi-publish:
    name: Save artifacts
    runs-on: ubuntu-latest
    needs: [build_wheels]
    environment:
      name: pypi
      url: https://pypi.org/p/pyKVFinder
    permissions:
      id-token: write

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - uses: actions/download-artifact@v4
        with:
          path: ./dist
          pattern: artifacts-*
          merge-multiple: true

      # - name: Publish package distributions to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}
