name: Integration Testing

on:
  release:
    types: [created]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .

      - name: Test with pytest
        run: |
          pytest tests/integration -v
